#!/bin/sh

FLX_DESK="$(cat /etc/flx-desktop 2>/dev/null || echo headless)"

if [ "$FLX_DESK" = "gui" ]; then
    case " $(cat /proc/cmdline 2>/dev/null) " in
        *" flx.autologin=1 "*)
            exec /usr/bin/flx-session
            ;;
    esac

    exec /usr/bin/greetd
fi

exec /bin/sh -l < /dev/tty1 > /dev/tty1 2>&1
