general {
    output_format = "none"
    colors = false
    interval = 2
}

order += "cpu_usage"
order += "memory"
order += "disk /"
order += "time"

cpu_usage {
    format = " cpu: %usage "
}

memory {
    format = " mem: %percentage_used "
}

disk "/" {
    format = " disk: %percentage_used "
}

time {
    format = " %a %b %d  %H:%M "
}